#!/bin/sh

set -e

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case "$1" in
prereqs)
	prereqs
	exit 0
	;;
esac

# The normal A733 initramfs leaves filesystem checks to the separate recovery
# image. It also excludes discrete PCI GPU payloads that this fixed A733 board
# cannot use; keeping them made the gzip result fluctuate around U-Boot's
# verified size boundary when otherwise identical initramfs images were rebuilt.
rm -f \
	"${DESTDIR}/usr/sbin/fsck" \
	"${DESTDIR}/usr/sbin/fsck.ext4" \
	"${DESTDIR}/usr/sbin/e2fsck" \
	"${DESTDIR}/usr/sbin/logsave" \
	"${DESTDIR}"/usr/lib/*/libcom_err.so.2* \
	"${DESTDIR}"/usr/lib/*/libe2p.so.2* \
	"${DESTDIR}"/usr/lib/*/libext2fs.so.2*

rm -rf \
	"${DESTDIR}/usr/lib/firmware/amdgpu" \
	"${DESTDIR}/usr/lib/firmware/nvidia"

find "${DESTDIR}/usr/lib/modules" -type f \
	\( -name 'amdgpu.ko*' -o -name 'nouveau.ko*' -o -name 'radeon.ko*' \) \
	-delete
